Refactor rust-clippy workflow and add error handling
Updated workflow names and added failure check for Clippy.

diff --git a/.github/workflows/rust-clippy.yml b/.github/workflows/rust-clippy.yml
--- a/.github/workflows/rust-clippy.yml
+++ b/.github/workflows/rust-clippy.yml
@@ -7,7 +7,7 @@
 # More details at https://github.com/rust-lang/rust-clippy
 # and https://rust-lang.github.io/rust-clippy/
 
-name: rust-clippy analyze
+name: Clippy Analyse
 
 on:
   push:
@@ -18,7 +18,7 @@ on:
 
 jobs:
   rust-clippy-analyze:
-    name: Run rust-clippy analyzing
+    name: Run rust-clippy analysing
     runs-on: ubuntu-latest
     permissions:
       contents: read
@@ -38,6 +38,7 @@ jobs:
         run: cargo install clippy-sarif sarif-fmt
 
       - name: Run rust-clippy
+        id: clippy
         run:
           cargo clippy
           --all-features
@@ -49,3 +50,8 @@ jobs:
         with:
           sarif_file: rust-clippy-results.sarif
           wait-for-processing: true
+
+        # Fail the action if errors are found
+      - name: CheckIfClippyFailed
+        if: steps.clippy.outcome == 'failure'
+        run: exit 1
